### ISSUE TITLE
Whiterun watch tower - spawned destryoyed/Missing?

### ISSUE THREAD

**Issue by Momma-Bee** [CritLoren/Yggdrasil-VR#91] opened 2023-06-11 21:57 UTC
**Describe the bug**
this is my first time posting to github bug reporting, so please forgive me if its not in the right format with posting pictures and such. 
-
Whiterun guardtower (the first one you encounter the vanilla dragon in) randomly decided not to spawn its parts, randomly an NPC would constantly re-spawn, fall and then repeat. getting close to the tower didn't fix it, and upon just looking into the tower, the npc just repeats falling and that's it. 

**To Reproduce**
1. Go to whiterun
2. visit the tower
3. ???

**Expected behavior**
im guessing something is suppose to be there. 

**Screenshots**

**Additional context**
I didn't change anything on the modpack, this was a fresh install (first install ever of the modpack) 

![20230611052600_1](https://github.com/CritLoren/Yggdrasil-VR/assets/101609689/be0d4ed5-b45b-438c-b1f2-8d391b720246)
![20230611052625_1](https://github.com/CritLoren/Yggdrasil-VR/assets/101609689/832ed698-11e2-4764-86b3-9936256bf128)

**Comment by CritLoren** [comment] 2023-06-11 22:21
Duplicate of #29

**Closed by CritLoren** 2023-06-11 22:21 UTC
Labels: bug
