### ISSUE TITLE
Floating ground objects at Legacy of the Dragonborn museum

### ISSUE THREAD

**Issue by CaptainWurstwasser** [CritLoren/Yggdrasil-VR#82] opened 2022-12-13 11:44 UTC
**Describe the bug**
In Solitude at the entrance to the museum there are floating ground objects

**To Reproduce**
Go to Solitude to the Legacy of the Dragonborn-museum

**Expected behavior**
Floating objects should not exist

**Screenshots**
![image](https://user-images.githubusercontent.com/120465455/207309113-895dcaf3-3ed6-4338-935e-2022c33f4ef3.png)

**Desktop:**
 - Yggdrasil VR version: 2.0-5

**Comment by CritLoren** [comment] 2022-12-13 12:51
Duplicate of #7

**Closed by CritLoren** 2022-12-13 12:51 UTC
Labels: bug
